# -*- coding: utf-8 -*-
"""iris_ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DPEz_msW39aWgnh3Xcg9NmCTWU_v4sdu
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

irisData = pd.read_csv('/content/drive/MyDrive/GoMyCode /iris.csv')

irisData.head(10)

irisData['variety'].value_counts()

iris_encoder = LabelEncoder()
irisData['variety'] = iris_encoder.fit_transform(irisData['variety'])

x = irisData.drop('variety', axis = 1)
y = irisData['variety']
x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

iris_model = LogisticRegression()
iris_model.fit(x_train, y_train)

y_pred = iris_model.predict(x_test)

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train, y_train)

y_pred_knn = knn.predict(x_test)
accuracy = accuracy_score(y_test, y_pred_knn)
print("Accuracy:", accuracy)

print(classification_report(y_test, y_pred_knn))
cm_knn = confusion_matrix(y_test, y_pred_knn)
print(cm_knn)

report = classification_report(y_test, y_pred)
print(report)
cm = confusion_matrix(y_test, y_pred)
print(cm)

print("Logistic Regression Accuracy:",
      accuracy_score(y_test, y_pred))

